# Generated by Django 4.0.3 on 2022-04-03 19:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_comments_remove_photos_comments_photos_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image_name',
            field=tinymce.models.HTMLField(),
        ),
    ]
