# Generated by Django 4.0.3 on 2022-04-04 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta', '0010_photos_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='comments',
        ),
        migrations.AddField(
            model_name='photos',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
